### ISSUE TITLE
Modrinth release?

### ISSUE THREAD

**Issue by SyberiaK** [altrisi/FastOpenLinksAndFolders#3]

**Comment by altrisi** [comment]
I actually have a page for it on modrinth, I just haven't uploaded jars there yet because it breaks the page design a little bit:

![imagen](https://user-images.githubusercontent.com/17107132/172930456-bddc7246-f087-4390-8128-de4421a1a53f.png)

Not sure when I'll get to uploading it, but it shouldn't be too long from now unless I forget.

**Comment by SyberiaK** [comment]
> I just haven't uploaded jars there yet because it breaks the page design a little bit

Bad advice (actually): rename the mod to something like "FastOpenThings" or use an abbreviation ("FOLAF")

**Comment by CodeF53** [comment]
![image](https://user-images.githubusercontent.com/37855219/173692197-b0b44943-c3a7-4ee2-b237-b096886e826e.png)
I think FXs idea of FastLinksAndFolders is a good idea for this

But also, I think this is only an issue in the edit page, because I have a mod with a super long name and that doesnt get cut off
![image](https://user-images.githubusercontent.com/37855219/173692445-7068d3e2-7c87-4d14-82f7-ed6019c130d9.png)

**Comment by altrisi** [comment]
This mod has no spaces, so it can't wrap.

I think I'll just not care about it and upload it like this.

**Comment by CodeF53** [comment]
Insert zero width spaces between the words, keeping the style of no spaces,
but allowing wrapping

**Comment by CodeF53** [comment]
Like this:

Fast​Open​Links​And​Folders

**Comment by SyberiaK** [comment]
> Insert zero width spaces between the words, keeping the style of no spaces, but allowing wrapping

***Is that even legit?***

**Comment by triphora** [comment]
I guess you'll be happy to know that this is fixed on the rewrite.
![image](https://user-images.githubusercontent.com/60205699/178089631-52da3d6b-96a1-43ef-a926-592685ba63b6.png)
https://rewrite.modrinth.com/mod/fastopenlinksandfolders
(Only project members [altrisi] and moderators [incl. me] can see this page)

**Comment by altrisi** [comment]
And it's out! https://modrinth.com/mod/fastopenlinksandfolders

Also thanks for the info about the rewrite!
